#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import textwrap
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


DEMO_ROADMAP = """# ROADMAP

```yaml
---
Project: "NexusRhythm Demo Workspace"
Project_Stage: "DELIVERY"
Current_Phase: "Phase 1 - Demo Workspace Bootstrapped"
Phase_Status: "DONE"
Active_Mode: 1
Pending_Debt: false
Debt_Deadline: null
Phases_Since_Vibe: 0
Idea_Clarity: 4
Target_User: "Developers evaluating the default NexusRhythm workflow in a clean Python project"
Core_Problem: "Need a minimal project that proves install, doctor, sync, and gate-check all work together"
Success_Metrics: "Demo workspace installs cleanly, passes doctor quick, and passes gate-check"
Primary_Risk: "If the demo inherits repository-specific state, the example becomes misleading"
Core_Tech_Stack: "Python, Markdown, Claude Code config, Bash hooks, Git"
---
```

---

## Project Goal

> A minimal demo workspace that proves NexusRhythm can bootstrap and validate a clean Python project.

## Phase Dashboard

| Phase | Name | Goal | Status | Phase_Status | Start | End |
|:----:|------|------|--------|:------------:|-------|-----|
| 1 | Demo bootstrap | Install scaffold and validate the first project loop | DONE | DONE | 2026-03-09 | 2026-03-09 |
| 2 | Demo customization | Extend the sample with a user-facing feature | Planned | — | — | — |

## Notes

- The demo starts in `DONE` so evaluators can immediately run `/sync`, `/doctor`, or `/phase-start`.
- `ROADMAP.md` remains the source of truth even in the demo.
"""


DEMO_README = """# NexusRhythm Demo Workspace

This workspace is generated by `scripts/create_demo_workspace.py`.

## What is included

- A tiny Python package with one tested function
- A project-local NexusRhythm install
- A ready-to-run `doctor quick` and `gate-check` path

## Suggested first commands

```bash
python3 scripts/nr.py sync
python3 scripts/nr.py doctor quick
python3 scripts/nr.py gate-check --no-update
```
"""


PYPROJECT = """[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nexusrhythm-demo"
version = "0.1.0"
description = "Minimal demo workspace for NexusRhythm"
requires-python = ">=3.11"
"""


CALCULATOR = """from __future__ import annotations


def add(left: int, right: int) -> int:
    return left + right
"""


TEST_DEMO_APP = """from __future__ import annotations

import unittest

from demo_app.calculator import add


class DemoAppTests(unittest.TestCase):
    def test_add(self) -> None:
        self.assertEqual(add(2, 3), 5)


if __name__ == "__main__":
    unittest.main()
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a minimal NexusRhythm demo workspace")
    parser.add_argument("target", help="Target directory for the demo workspace")
    return parser.parse_args()


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


def ensure_target(target: Path) -> int:
    if target.exists() and not target.is_dir():
        return fail(f"Target path is not a directory: {target}")
    if target.exists() and any(target.iterdir()):
        return fail(f"Target directory is not empty: {target}")
    target.mkdir(parents=True, exist_ok=True)
    return 0


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(content).strip() + "\n", encoding="utf-8")


def install_scaffold(target: Path) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["NEXUSRHYTHM_SOURCE_DIR"] = str(REPO_ROOT)
    return subprocess.run(
        ["bash", str(REPO_ROOT / "install.sh"), str(target)],
        cwd=REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def main() -> int:
    args = parse_args()
    target = Path(args.target).resolve()
    status = ensure_target(target)
    if status != 0:
        return status

    write_file(target / "ROADMAP.md", DEMO_ROADMAP)
    write_file(target / "README.md", DEMO_README)
    write_file(target / "pyproject.toml", PYPROJECT)
    write_file(target / "demo_app" / "__init__.py", "")
    write_file(target / "demo_app" / "calculator.py", CALCULATOR)
    write_file(target / "tests" / "test_demo_app.py", TEST_DEMO_APP)

    install_result = install_scaffold(target)
    if install_result.returncode != 0:
        sys.stderr.write(install_result.stderr or install_result.stdout)
        return install_result.returncode

    print(f"Created demo workspace: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
